import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-state-tax-apportionment-nol-recovery",
  "engine": "recovery",
  "title": "State Tax Apportionment & NOL Recovery",
  "shortTitle": "State Tax Apportionment and NOL Recovery",
  "tagline": "Quantify, recover, and prevent financial leakage through state tax apportionment & nol recovery",
  "industry": "Multi-State Income Tax Recovery",
  "uiPort": 4632,
  "apiPort": 5632,
  "accent": "#0f766e",
  "currency": "USD",
  "primaryOutcome": "State Tax Apportionment & NOL Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect legal entities, filing groups, state rules, revenue sourcing, payroll, property, market sourcing, throwback, combined reporting, NOL vintages, credits, provisions, returns, and refunds in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "receivedRefund",
    "expectedKey": "eligibleRefund",
    "actualLabel": "Received State Tax Benefit",
    "expectedLabel": "Calculated Eligible Benefit",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "State Tax Apportionment & NOL Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("entity-filing-group-registry","STA01","Entity filing-group registry","Execute entity filing-group registry using legal entities, filing groups, state rules, revenue sourcing, payroll, property, market sourcing, throwback, combined reporting, NOL vintages, credits, provisions, returns, and refunds.","Produce a governed entity filing-group registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Legal Entity / Tax Year","text","Legal Entity / Tax Year · Standard Case"],["caseReference","Entity filing-group registry Reference","text","STA01-2026-001"],["receivedRefund","Received State Tax Benefit","currency",1178500],["eligibleRefund","Calculated Eligible Benefit","currency",1390630],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Entity filing-group registry case","State rule library case","Revenue sourcing case","Payroll factor calculation case","Property factor calculation case"]}),
feature("state-rule-library","STA02","State rule library","Execute state rule library using legal entities, filing groups, state rules, revenue sourcing, payroll, property, market sourcing, throwback, combined reporting, NOL vintages, credits, provisions, returns, and refunds.","Produce a governed state rule library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Legal Entity / Tax Year","text","Legal Entity / Tax Year · Standard Case"],["caseReference","State rule library Reference","text","STA02-2026-001"],["receivedRefund","Received State Tax Benefit","currency",1178500],["eligibleRefund","Calculated Eligible Benefit","currency",1390630],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Entity filing-group registry case","State rule library case","Revenue sourcing case","Payroll factor calculation case","Property factor calculation case"]}),
feature("revenue-sourcing","STA03","Revenue sourcing","Execute revenue sourcing using legal entities, filing groups, state rules, revenue sourcing, payroll, property, market sourcing, throwback, combined reporting, NOL vintages, credits, provisions, returns, and refunds.","Produce a governed revenue sourcing decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Legal Entity / Tax Year","text","Legal Entity / Tax Year · Standard Case"],["caseReference","Revenue sourcing Reference","text","STA03-2026-001"],["receivedRefund","Received State Tax Benefit","currency",1178500],["eligibleRefund","Calculated Eligible Benefit","currency",1390630],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Entity filing-group registry case","State rule library case","Revenue sourcing case","Payroll factor calculation case","Property factor calculation case"]}),
feature("payroll-factor-calculation","STA04","Payroll factor calculation","Execute payroll factor calculation using legal entities, filing groups, state rules, revenue sourcing, payroll, property, market sourcing, throwback, combined reporting, NOL vintages, credits, provisions, returns, and refunds.","Produce a governed payroll factor calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Legal Entity / Tax Year","text","Legal Entity / Tax Year · Standard Case"],["caseReference","Payroll factor calculation Reference","text","STA04-2026-001"],["receivedRefund","Received State Tax Benefit","currency",1178500],["eligibleRefund","Calculated Eligible Benefit","currency",1390630],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Entity filing-group registry case","State rule library case","Revenue sourcing case","Payroll factor calculation case","Property factor calculation case"]}),
feature("property-factor-calculation","STA05","Property factor calculation","Execute property factor calculation using legal entities, filing groups, state rules, revenue sourcing, payroll, property, market sourcing, throwback, combined reporting, NOL vintages, credits, provisions, returns, and refunds.","Produce a governed property factor calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Legal Entity / Tax Year","text","Legal Entity / Tax Year · Standard Case"],["caseReference","Property factor calculation Reference","text","STA05-2026-001"],["receivedRefund","Received State Tax Benefit","currency",1178500],["eligibleRefund","Calculated Eligible Benefit","currency",1390630],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Entity filing-group registry case","State rule library case","Revenue sourcing case","Payroll factor calculation case","Property factor calculation case"]}),
feature("market-based-sourcing","STA06","Market-based sourcing","Execute market-based sourcing using legal entities, filing groups, state rules, revenue sourcing, payroll, property, market sourcing, throwback, combined reporting, NOL vintages, credits, provisions, returns, and refunds.","Produce a governed market-based sourcing decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Legal Entity / Tax Year","text","Legal Entity / Tax Year · Standard Case"],["caseReference","Market-based sourcing Reference","text","STA06-2026-001"],["receivedRefund","Received State Tax Benefit","currency",1178500],["eligibleRefund","Calculated Eligible Benefit","currency",1390630],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Entity filing-group registry case","State rule library case","Revenue sourcing case","Payroll factor calculation case","Property factor calculation case"]}),
feature("throwback-throwout-rules","STA07","Throwback throwout rules","Execute throwback throwout rules using legal entities, filing groups, state rules, revenue sourcing, payroll, property, market sourcing, throwback, combined reporting, NOL vintages, credits, provisions, returns, and refunds.","Produce a governed throwback throwout rules decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Legal Entity / Tax Year","text","Legal Entity / Tax Year · Standard Case"],["caseReference","Throwback throwout rules Reference","text","STA07-2026-001"],["receivedRefund","Received State Tax Benefit","currency",1178500],["eligibleRefund","Calculated Eligible Benefit","currency",1390630],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Entity filing-group registry case","State rule library case","Revenue sourcing case","Payroll factor calculation case","Property factor calculation case"]}),
feature("combined-reporting-control","STA08","Combined reporting control","Execute combined reporting control using legal entities, filing groups, state rules, revenue sourcing, payroll, property, market sourcing, throwback, combined reporting, NOL vintages, credits, provisions, returns, and refunds.","Produce a governed combined reporting control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Legal Entity / Tax Year","text","Legal Entity / Tax Year · Standard Case"],["caseReference","Combined reporting control Reference","text","STA08-2026-001"],["receivedRefund","Received State Tax Benefit","currency",1178500],["eligibleRefund","Calculated Eligible Benefit","currency",1390630],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Entity filing-group registry case","State rule library case","Revenue sourcing case","Payroll factor calculation case","Property factor calculation case"]}),
feature("nol-vintage-ledger","STA09","NOL vintage ledger","Execute nol vintage ledger using legal entities, filing groups, state rules, revenue sourcing, payroll, property, market sourcing, throwback, combined reporting, NOL vintages, credits, provisions, returns, and refunds.","Produce a governed nol vintage ledger decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Legal Entity / Tax Year","text","Legal Entity / Tax Year · Standard Case"],["caseReference","NOL vintage ledger Reference","text","STA09-2026-001"],["receivedRefund","Received State Tax Benefit","currency",1178500],["eligibleRefund","Calculated Eligible Benefit","currency",1390630],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Entity filing-group registry case","State rule library case","Revenue sourcing case","Payroll factor calculation case","Property factor calculation case"]}),
feature("limitation-expiration-calculation","STA10","Limitation expiration calculation","Execute limitation expiration calculation using legal entities, filing groups, state rules, revenue sourcing, payroll, property, market sourcing, throwback, combined reporting, NOL vintages, credits, provisions, returns, and refunds.","Produce a governed limitation expiration calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Legal Entity / Tax Year","text","Legal Entity / Tax Year · Standard Case"],["caseReference","Limitation expiration calculation Reference","text","STA10-2026-001"],["receivedRefund","Received State Tax Benefit","currency",1178500],["eligibleRefund","Calculated Eligible Benefit","currency",1390630],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Entity filing-group registry case","State rule library case","Revenue sourcing case","Payroll factor calculation case","Property factor calculation case"]}),
feature("credit-inventory","STA11","Credit inventory","Execute credit inventory using legal entities, filing groups, state rules, revenue sourcing, payroll, property, market sourcing, throwback, combined reporting, NOL vintages, credits, provisions, returns, and refunds.","Produce a governed credit inventory decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Legal Entity / Tax Year","text","Legal Entity / Tax Year · Standard Case"],["caseReference","Credit inventory Reference","text","STA11-2026-001"],["receivedRefund","Received State Tax Benefit","currency",1178500],["eligibleRefund","Calculated Eligible Benefit","currency",1390630],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Entity filing-group registry case","State rule library case","Revenue sourcing case","Payroll factor calculation case","Property factor calculation case"]}),
feature("provision-return-reconciliation","STA12","Provision return reconciliation","Execute provision return reconciliation using legal entities, filing groups, state rules, revenue sourcing, payroll, property, market sourcing, throwback, combined reporting, NOL vintages, credits, provisions, returns, and refunds.","Produce a governed provision return reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Legal Entity / Tax Year","text","Legal Entity / Tax Year · Standard Case"],["caseReference","Provision return reconciliation Reference","text","STA12-2026-001"],["receivedRefund","Received State Tax Benefit","currency",1178500],["eligibleRefund","Calculated Eligible Benefit","currency",1390630],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Entity filing-group registry case","State rule library case","Revenue sourcing case","Payroll factor calculation case","Property factor calculation case"]}),
feature("amended-return-opportunity","STA13","Amended return opportunity","Execute amended return opportunity using legal entities, filing groups, state rules, revenue sourcing, payroll, property, market sourcing, throwback, combined reporting, NOL vintages, credits, provisions, returns, and refunds.","Produce a governed amended return opportunity decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Legal Entity / Tax Year","text","Legal Entity / Tax Year · Standard Case"],["caseReference","Amended return opportunity Reference","text","STA13-2026-001"],["receivedRefund","Received State Tax Benefit","currency",1178500],["eligibleRefund","Calculated Eligible Benefit","currency",1390630],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Entity filing-group registry case","State rule library case","Revenue sourcing case","Payroll factor calculation case","Property factor calculation case"]}),
feature("refund-tracking","STA14","Refund tracking","Execute refund tracking using legal entities, filing groups, state rules, revenue sourcing, payroll, property, market sourcing, throwback, combined reporting, NOL vintages, credits, provisions, returns, and refunds.","Produce a governed refund tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Legal Entity / Tax Year","text","Legal Entity / Tax Year · Standard Case"],["caseReference","Refund tracking Reference","text","STA14-2026-001"],["receivedRefund","Received State Tax Benefit","currency",1178500],["eligibleRefund","Calculated Eligible Benefit","currency",1390630],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Entity filing-group registry case","State rule library case","Revenue sourcing case","Payroll factor calculation case","Property factor calculation case"]}),
feature("state-entity-analytics","STA15","State entity analytics","Execute state entity analytics using legal entities, filing groups, state rules, revenue sourcing, payroll, property, market sourcing, throwback, combined reporting, NOL vintages, credits, provisions, returns, and refunds.","Produce a governed state entity analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Legal Entity / Tax Year","text","Legal Entity / Tax Year · Standard Case"],["caseReference","State entity analytics Reference","text","STA15-2026-001"],["receivedRefund","Received State Tax Benefit","currency",1178500],["eligibleRefund","Calculated Eligible Benefit","currency",1390630],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Entity filing-group registry case","State rule library case","Revenue sourcing case","Payroll factor calculation case","Property factor calculation case"]})
]);
